volumes:
  sqlservervolume: {}
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Admin#1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    volumes:
      - sqlservervolume:/var/opt/mssql

  api:
    environment:
      OnboardingDB: ${OnboardingDB}
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:8080
    build:
      context: .
      dockerfile: Apps/Onboarding.API/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - "db"

  worker:
    environment:
      OnboardingDB: ${OnboardingDB}
    build:
      context: .
      dockerfile: Apps/Onboarding.Worker/Dockerfile
    depends_on:
      - "db"
