volumes:
  sqlservervolume: {}
services:
  SqlServer:
    image: "mcr.microsoft.com/mssql/server:2019-latest-ubuntu"
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Admin#1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    volumes:
      - sqlservervolume:/var/opt/mssql
